ltss6 and 7
Enterprise-CMCS/macpro-mdct-hcbs pull request #76
Opened 2024-12-11 15:08 UTC by ajaitasaini

### Description

### Related ticket(s)

CMDCT-

---
### How to test

### Important updates

---
### Author checklist

- [ ] I have performed a self-review of my code
- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
- [ ] I have updated relevant documentation, if necessary
---

_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → prod](?expand=1&template=val-to-prod-deployment.md)_

2024-12-11 18:21 UTC, BearHanded submitted a review, later dismissed

2024-12-11 18:59 UTC, rocio-desantiago requested changes
Remove the question: "What Technical Specifications are you using to report this measure?" 
That one only applies to LTSS-1, LTSS-2, LTSS-3, LTSS-4 Measures

2024-12-11 19:16 UTC, rocio-desantiago commented on services/app-api/forms/cmit.ts
> +    dataSource: DataSource.Hybrid,
Found out that LTSS-6 has an Administrative dataSource in this [file](https://docs.google.com/spreadsheets/d/1ztZ1DSYCUkKz9E_np5q-k9CgBoHYKEWUc_Fd2t3RJmc/edit?gid=1582150716#gid=1582150716)

2024-12-11 19:18 UTC, rocio-desantiago requested changes
From this [excel sheet](https://docs.google.com/spreadsheets/d/1ztZ1DSYCUkKz9E_np5q-k9CgBoHYKEWUc_Fd2t3RJmc/edit?gid=1582150716#gid=1582150716) - that should have been on the ticket lol
measure spec is only CMS for all 3, delivery system still has both MLTSS and FSS and Administrative instead of Hybrid Data source

2024-12-11 19:46 UTC, rocio-desantiago approved these changes
Looks good 👍

2024-12-12 14:30 UTC, angelaco11 approved these changes
Looks good to me!

2024-12-12 14:30 UTC, merged